### ISSUE TITLE
Boxer

### ISSUE THREAD

**Issue by Malivil** [NoxxFlame/TTT-Jingle-Jam-Roles-2021#1]
- Suggested by: Fyxen
- Team: Jester
- Description: A jester role that can box people.
-----
### Role Specifics
They have a custom boxing gloves melee weapon that:
- Causes players to ragdoll
- Makes players drop their weapons

### Open Questions
- The boxing gloves will have a charge-up attack, what do we want to use that for?
  - Charge-up is the one that causes a player to ragdoll
    - Play the "ding ding ding" sound when they get ragdolled
    - Stays knocked down for a long-ish timer (20 seconds? scales up each time they are knocked down?) or until someone picks them up
      - Can we put some "dizziness" indicator around knocked down players?
    - Ragdolled players can still take damage
  - Normal hit just makes them drop their current weapon
- What is the win condition?
  - If everyone else is dead or knocked out, they win
-----
### Tasks
- [x] Create role
  - [x] Win condition
    - [x] Logic
    - [x] Events
  - [x] Tutorial
  - [x] Popup
  - [x] Knockout
    - [x] "ding ding" sound
    - [x] "dizzy" effect
    - [x] Ragdoll
    - [x] Allow other players to revive
    - [x] Transfer damage from ragdoll
    - [x] Show knockout progress bar
- [x] Convars
  - [x] Ragdoll time
  - [x] Percent chance for attack to drop weapon
- [x] Graphics
  - [x] Tab
  - [x] Score
  - [x] Sprite
  - [x] Icon
  - [x] Workshop
- [x] Create boxing gloves
  - [x] Model (Fyxen)
  - [x] Animations (Fyxen)
  - [x] Textures (Fyxen)
  - [x] Weapon code
    - [x] Translations
    - [x] Attack
      - [x] Cause target to drop current weapon based on percent chance
    - [x] Flurry attack
      - [x] Scream
      - [x] Hit-per-animation hit
      - [x] Knockout player
