### ISSUE TITLE
Communist

### ISSUE THREAD

**Issue by Malivil** [NoxxFlame/TTT-Jingle-Jam-Roles-2021#2]
- Suggested by: Horselover Fat
- Team: Independent
- Description: An independent who is spreading communism to the masses
-----
### Role Specifics
> Give someone the Communist Manifesto (starting item, can be reused) to make them a Communist. All non-Communists gain a credit when someone becomes a Communist. Become detective if communism randomat. If the Communists lose, end screen says “Capitalism and [winning team] win.”

### Open Questions
- What existing model should we use for the Communist Manifesto?
- How does the Communist Manifesto convert someone?
  - Can the person run away, or are they locked in place like the Vampire fangs?
-----
### Tasks
- [x] Create role
  - [x] Custom win condition
  - [x] Custom lose message (using new expanded secondary roles support)
  - [x] Tutorial
- [x] Convars
  - [x] Credit reward amount
  - [x] Communist Manifesto usage time
- [x] Graphics
  - [x] Tab
  - [x] Score
  - [x] Sprite
  - [x] Icon
  - [x] Workshop
- [x] Communist Manifesto
  - [x] Model (Fyxen)
  - [x] Animations (Fyxen)
  - [x] Textures (Fyxen)
  - [x] Weapon code
    - [x] Convert
    - [x] Give credits
    - [x] Play sound while converting
    - [x] Animations

**Comment by Malivil** [comment]
ACT_VM_IDLE = 240 at 24fps
ACT_VM_PRIMARYATTACK = 24 at 24fps
ACT_VM_DRAW = 32 at 24fps
